# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2024
  # 文件路径
  profile: /home/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 生产环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: info
    org.springframework: warn

# 数据源配置
spring:
    # 资源信息
    messages:
        # 国际化资源文件路径
        basename: i18n/messages
    # 文件上传
    servlet:
        multipart:
            # 单个文件大小
            max-file-size: 10MB
            # 设置总上传的文件大小
            max-request-size: 20MB
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ruoyi-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: ruoyi
        password: ZN2bBnciAmyf7NaG
        hikari:
            # 连接池名称
            pool-name: HikariPool
            # 最小空闲连接数量
            minimum-idle: 20
            # 最大连接池数量
            maximum-pool-size: 100
            # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
            auto-commit: true
            # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
            max-lifetime: 1800000
            # 数据库连接超时时间,默认30秒，即30000
            connection-timeout: 30000
            # 此属性控制连接可以在池中闲置的最长时间，值0表示永远不会从池中删除空闲连接，默认600000即10分钟
            idle-timeout: 600000
            # 此属性控制连接测试活跃度的最大时间间隔，默认值为0（禁用），最小允许值为30000ms（30秒）
            keepalive-time: 0
            # 此属性确定连接是否在事务中可以被池暂停。推荐值：true
            allow-pool-suspension: true
            # 只读数据库
            read-only: false
            # 检测连接是否有效
            connection-test-query: SELECT 1
    # redis 配置
    data:
        redis:
            # 地址
            host: localhost
            # 端口，默认为6379
            port: 6379
            # 数据库索引
            database: 0
            # 密码
            password: 
            # 连接超时时间
            timeout: 10s
            lettuce:
                pool:
                    # 连接池中的最小空闲连接
                    min-idle: 0
                    # 连接池中的最大空闲连接
                    max-idle: 8
                    # 连接池的最大数据库连接数
                    max-active: 8
                    # 连接池最大阻塞等待时间（使用负值表示没有限制）
                    max-wait: -1ms

# Sa-Token配置
sa-token:
    # token名称 (同时也是cookie名称)
    token-name: Authorization
    # token有效期，单位s 默认30天, 设置为一天
    timeout: 86400
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
    # 是否输出操作日志
    is-log: true 

# Swagger配置
swagger:
    # 是否开启swagger
    enabled: true
    # 请求前缀
    pathMapping: /dev-api

# 防止XSS攻击
xss:
    # 过滤开关
    enabled: false
    # 排除链接（个用逗号分隔）
    excludes: /system/notice
    # 匹配链接
    urlPatterns: /system/*,/monitor/*,/tool/*