CREATE TABLE IF NOT EXISTS `mini_app` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `app_code` varchar(64) NOT NULL,
  `app_name` varchar(128) NOT NULL,
  `platform` varchar(32) NOT NULL DEFAULT 'wechat_ma',
  `app_id` varchar(64) NOT NULL,
  `app_secret` varchar(128) NOT NULL,
  `token` varchar(128) DEFAULT NULL,
  `aes_key` varchar(128) DEFAULT NULL,
  `enabled` char(1) NOT NULL DEFAULT 'Y',
  `status` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mini_app_code` (`app_code`),
  UNIQUE KEY `uk_mini_app_appid` (`app_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序应用配置';

CREATE TABLE IF NOT EXISTS `mini_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `nickname` varchar(128) DEFAULT NULL,
  `avatar` varchar(500) DEFAULT NULL,
  `mobile` varchar(32) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `source_app_code` varchar(64) DEFAULT NULL,
  `last_login_time` datetime DEFAULT NULL,
  `status` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序用户主体';

CREATE TABLE IF NOT EXISTS `mini_user_auth` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `mini_user_id` bigint NOT NULL,
  `mini_app_id` bigint NOT NULL,
  `platform` varchar(32) NOT NULL DEFAULT 'wechat_ma',
  `openid` varchar(128) NOT NULL,
  `unionid` varchar(128) DEFAULT NULL,
  `session_key` varchar(255) DEFAULT NULL,
  `nickname` varchar(128) DEFAULT NULL,
  `avatar` varchar(500) DEFAULT NULL,
  `raw_json` text,
  `bind_time` datetime DEFAULT NULL,
  `last_login_time` datetime DEFAULT NULL,
  `status` char(1) NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mini_app_openid` (`mini_app_id`, `openid`),
  KEY `idx_mini_user_auth_user` (`mini_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序用户授权绑定';

CREATE TABLE IF NOT EXISTS `translate_document` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `mini_user_id` bigint NOT NULL,
  `mini_app_id` bigint NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `file_ext` varchar(32) NOT NULL,
  `mime_type` varchar(128) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `content_hash` varchar(128) DEFAULT NULL,
  `source_oss_url` varchar(1000) NOT NULL,
  `source_oss_key` varchar(500) NOT NULL,
  `parse_status` varchar(32) NOT NULL DEFAULT 'pending',
  `status` varchar(32) NOT NULL DEFAULT 'uploaded',
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_translate_document_owner` (`mini_user_id`, `mini_app_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='翻译文档';

CREATE TABLE IF NOT EXISTS `translate_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `mini_user_id` bigint NOT NULL,
  `mini_app_id` bigint NOT NULL,
  `document_id` bigint NOT NULL,
  `product_type` varchar(64) NOT NULL DEFAULT 'miniapp',
  `scene_code` varchar(64) NOT NULL DEFAULT 'doc_translate',
  `source_language` varchar(32) DEFAULT NULL,
  `target_language` varchar(32) NOT NULL,
  `output_format` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `progress` int NOT NULL DEFAULT '0',
  `model_config_id` bigint DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `result_oss_url` varchar(1000) DEFAULT NULL,
  `result_oss_key` varchar(500) DEFAULT NULL,
  `preview_oss_url` varchar(1000) DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` varchar(1000) DEFAULT NULL,
  `retry_count` int NOT NULL DEFAULT '0',
  `started_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_translate_task_owner` (`mini_user_id`, `mini_app_id`),
  KEY `idx_translate_task_document` (`document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='翻译任务';

CREATE TABLE IF NOT EXISTS `translate_segment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `segment_no` int NOT NULL,
  `segment_type` varchar(32) DEFAULT NULL,
  `source_text` longtext,
  `translated_text` longtext,
  `placeholder_map` longtext,
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `token_input` int DEFAULT NULL,
  `token_output` int DEFAULT NULL,
  `error_message` varchar(1000) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` char(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_translate_segment_task` (`task_id`, `segment_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='翻译分段';
